blank_issues_enabled: false
contact_links:
  - name: Herald project website
    url: https://heraldprox.io
    about: Our main project website for information
  - name: Developer and integration guides
    url: https://heraldprox.io/guide/
    about: Please review this guide for how to integrate Herald with your application
  - name: Herald community
    url: https://heraldprox.io/community
    about: Please join the Herald community to ask questions and get involved with development